name: python-tests

on:
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
